import type { Product, Event, Wallet, Transaction, SavedCard, Cause } from './types';

export const sectors = [
    'Technology', 'Healthcare', 'Finance', 'Education', 'Manufacturing',
    'Retail', 'Real Estate', 'Agriculture', 'Energy', 'Media',
    'Non-Profit', 'Government'
].map((name, i) => ({ id: `sec-${i}`, name }));

export const countries = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
  "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic",
  "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
  "Fiji", "Finland", "France",
  "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Honduras", "Hungary",
  "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
  "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan",
  "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
  "Oman",
  "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar",
  "Romania", "Russia", "Rwanda",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
  "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
  "Yemen",
  "Zambia", "Zimbabwe"
];


export const regions = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", 
  "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", 
  "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", 
  "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
  "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
];

export const globalRegions = [
  { name: "Africa", members: 12500, hubs: 45 },
  { name: "North America", members: 8200, hubs: 32 },
  { name: "Europe", members: 6800, hubs: 28 },
  { name: "Asia Pacific", members: 9400, hubs: 38 },
  { name: "Latin America", members: 5600, hubs: 22 },
];


export const continents = [
    "Africa",
    "Asia",
    "Europe",
    "North America",
    "South America",
    "Oceania"
];

export const roles = [
  { id: "mentee", title: "Mentee", description: "Learn and receive mentorship.", icon: "🎓" },
  { id: "mentor-candidate", title: "Mentor Candidate", description: "Begin the journey to become a certified mentor.", icon: "🌱" },
  { id: "associate-mentor", title: "Associate (High-Pedigree Mentor)", description: "Apply for verification as an experienced mentor.", icon: "✨" },
  { id: "collaborator", title: "Collaborator", description: "Support TGN programs and projects.", icon: "🤝" },
  { id: "sponsor", title: "Sponsor", description: "Fund or partner with TGN initiatives.", icon: "💎" },
  { id: "country-manager", title: "Country Manager", description: "Coordinate regional network growth.", icon: "🌍" },
  { id: "admin", title: "Admin", description: "Full administrative access to the platform.", icon: "Shield" },
  { id: "volunteer", title: "Volunteer", description: "Support community operations and events.", icon: "❤️" },
  { id: "media", title: "Media", description: "Share our impact and stories with the world.", icon: "📢" },
];

export const goals = [
  "Find a mentor", "Become a mentor", "Grow my network", 
  "Learn new skills", "Start a business", "Career transition",
  "Give back to community", "Find collaborators"
];

export const badgeLevels = ["All Levels", "★ 1", "★ 2", "★ 3", "★ 4", "★ 5", "★ 6", "★ 7"];

export const mentorTypes = ["All Types", "Associate Mentor", "Certified Mentor", "Executive Mentor"];

export const products: Product[] = [];
export const events: Event[] = [];

export const timezones = [
    { value: 'Africa/Abidjan', label: '(GMT+00:00) Abidjan' },
    { value: 'Africa/Accra', label: '(GMT+00:00) Accra' },
    { value: 'Africa/Addis_Ababa', label: '(GMT+03:00) Addis Ababa' },
    { value: 'Africa/Algiers', label: '(GMT+01:00) Algiers' },
    { value: 'Africa/Asmara', label: '(GMT+03:00) Asmara' },
    { value: 'Africa/Bamako', label: '(GMT+00:00) Bamako' },
    { value: 'Africa/Bangui', label: '(GMT+01:00) Bangui' },
    { value: 'Africa/Banjul', label: '(GMT+00:00) Banjul' },
    { value: 'Africa/Bissau', label: '(GMT+00:00) Bissau' },
    { value: 'Africa/Blantyre', label: '(GMT+02:00) Blantyre' },
    { value: 'Africa/Brazzaville', label: '(GMT+01:00) Brazzaville' },
    { value: 'Africa/Bujumbura', label: '(GMT+02:00) Bujumbura' },
    { value: 'Africa/Cairo', label: '(GMT+02:00) Cairo' },
    { value: 'Africa/Casablanca', label: '(GMT+01:00) Casablanca' },
    { value: 'Africa/Ceuta', label: '(GMT+02:00) Ceuta' },
    { value: 'Africa/Conakry', label: '(GMT+00:00) Conakry' },
    { value: 'Africa/Dakar', label: '(GMT+00:00) Dakar' },
    { value: 'Africa/Dar_es_Salaam', label: '(GMT+03:00) Dar es Salaam' },
    { value: 'Africa/Djibouti', label: '(GMT+03:00) Djibouti' },
    { value: 'Africa/Douala', label: '(GMT+01:00) Douala' },
    { value: 'Africa/El_Aaiun', label: '(GMT+01:00) El Aaiun' },
    { value: 'Africa/Freetown', label: '(GMT+00:00) Freetown' },
    { value: 'Africa/Gaborone', label: '(GMT+02:00) Gaborone' },
    { value: 'Africa/Harare', label: '(GMT+02:00) Harare' },
    { value: 'Africa/Johannesburg', label: '(GMT+02:00) Johannesburg' },
    { value: 'Africa/Juba', label: '(GMT+02:00) Juba' },
    { value: 'Africa/Kampala', label: '(GMT+03:00) Kampala' },
    { value: 'Africa/Khartoum', label: '(GMT+02:00) Khartoum' },
    { value: 'Africa/Kigali', label: '(GMT+02:00) Kigali' },
    { value: 'Africa/Kinshasa', label: '(GMT+01:00) Kinshasa' },
    { value: 'Africa/Lagos', label: '(GMT+01:00) Lagos' },
    { value: 'Africa/Libreville', label: '(GMT+01:00) Libreville' },
    { value: 'Africa/Lome', label: '(GMT+00:00) Lome' },
    { value: 'Africa/Luanda', label: '(GMT+01:00) Luanda' },
    { value: 'Africa/Lubumbashi', label: '(GMT+02:00) Lubumbashi' },
    { value: 'Africa/Lusaka', label: '(GMT+02:00) Lusaka' },
    { value: 'Africa/Malabo', label: '(GMT+01:00) Malabo' },
    { value: 'Africa/Maputo', label: '(GMT+02:00) Maputo' },
    { value: 'Africa/Maseru', label: '(GMT+02:00) Maseru' },
    { value: 'Africa/Mbabane', label: '(GMT+02:00) Mbabane' },
    { value: 'Africa/Mogadishu', label: '(GMT+03:00) Mogadishu' },
    { value: 'Africa/Monrovia', label: '(GMT+00:00) Monrovia' },
    { value: 'Africa/Nairobi', label: '(GMT+03:00) Nairobi' },
    { value: 'Africa/Ndjamena', label: '(GMT+01:00) Ndjamena' },
    { value: 'Africa/Niamey', label: '(GMT+01:00) Niamey' },
    { value: 'Africa/Nouakchott', label: '(GMT+00:00) Nouakchott' },
    { value: 'Africa/Ouagadougou', label: '(GMT+00:00) Ouagadougou' },
    { value: 'Africa/Porto-Novo', label: '(GMT+01:00) Porto-Novo' },
    { value: 'Africa/Sao_Tome', label: '(GMT+00:00) Sao Tome' },
    { value: 'Africa/Tripoli', label: '(GMT+02:00) Tripoli' },
    { value: 'Africa/Tunis', label: '(GMT+01:00) Tunis' },
    { value: 'Africa/Windhoek', label: '(GMT+02:00) Windhoek' },
    { value: 'America/Adak', label: '(GMT-09:00) Adak' },
    { value: 'America/Anchorage', label: '(GMT-08:00) Anchorage' },
    { value: 'America/Anguilla', label: '(GMT-04:00) Anguilla' },
    { value: 'America/Antigua', label: '(GMT-04:00) Antigua' },
    { value: 'America/Araguaina', label: '(GMT-03:00) Araguaina' },
    { value: 'America/Argentina/Buenos_Aires', label: '(GMT-03:00) Argentina/Buenos Aires' },
    { value: 'America/Argentina/Catamarca', label: '(GMT-03:00) Argentina/Catamarca' },
    { value: 'America/Argentina/Cordoba', label: '(GMT-03:00) Argentina/Cordoba' },
    { value: 'America/Argentina/Jujuy', label: '(GMT-03:00) Argentina/Jujuy' },
    { value: 'America/Argentina/La_Rioja', label: '(GMT-03:00) Argentina/La Rioja' },
    { value: 'America/Argentina/Mendoza', label: '(GMT-03:00) Argentina/Mendoza' },
    { value: 'America/Argentina/Rio_Gallegos', label: '(GMT-03:00) Argentina/Rio Gallegos' },
    { value: 'America/Argentina/Salta', label: '(GMT-03:00) Argentina/Salta' },
    { value: 'America/Argentina/San_Juan', label: '(GMT-03:00) Argentina/San Juan' },
    { value: 'America/Argentina/San_Luis', label: '(GMT-03:00) Argentina/San Luis' },
    { value: 'America/Argentina/Tucuman', label: '(GMT-03:00) Argentina/Tucuman' },
    { value: 'America/Argentina/Ushuaia', label: '(GMT-03:00) Argentina/Ushuaia' },
    { value: 'America/Aruba', label: '(GMT-04:00) Aruba' },
    { value: 'America/Asuncion', label: '(GMT-04:00) Asuncion' },
    { value: 'America/Atikokan', label: '(GMT-05:00) Atikokan' },
    { value: 'America/Bahia', label: '(GMT-03:00) Bahia' },
    { value: 'America/Bahia_Banderas', label: '(GMT-06:00) Bahia Banderas' },
    { value: 'America/Barbados', label: '(GMT-04:00) Barbados' },
    { value: 'America/Belem', label: '(GMT-03:00) Belem' },
    { value: 'America/Belize', label: '(GMT-06:00) Belize' },
    { value: 'America/Blanc-Sablon', label: '(GMT-04:00) Blanc-Sablon' },
    { value: 'America/Boa_Vista', label: '(GMT-04:00) Boa Vista' },
    { value: 'America/Bogota', label: '(GMT-05:00) Bogota' },
    { value: 'America/Boise', label: '(GMT-06:00) Boise' },
    { value: 'America/Cambridge_Bay', label: '(GMT-06:00) Cambridge Bay' },
    { value: 'America/Campo_Grande', label: '(GMT-04:00) Campo Grande' },
    { value: 'America/Cancun', label: '(GMT-05:00) Cancun' },
    { value: 'America/Caracas', label: '(GMT-04:00) Caracas' },
    { value: 'America/Cayenne', label: '(GMT-03:00) Cayenne' },
    { value: 'America/Cayman', label: '(GMT-05:00) Cayman' },
    { value: 'America/Chicago', label: '(GMT-05:00) Chicago' },
    { value: 'America/Chihuahua', label: '(GMT-06:00) Chihuahua' },
    { value: 'America/Ciudad_Juarez', label: '(GMT-06:00) Ciudad Juarez' },
    { value: 'America/Costa_Rica', label: '(GMT-06:00) Costa Rica' },
    { value: 'America/Creston', label: '(GMT-07:00) Creston' },
    { value: 'America/Cuiaba', label: '(GMT-04:00) Cuiaba' },
    { value: 'America/Curacao', label: '(GMT-04:00) Curacao' },
    { value: 'America/Danmarkshavn', label: '(GMT+00:00) Danmarkshavn' },
    { value: 'America/Dawson', label: '(GMT-07:00) Dawson' },
    { value: 'America/Dawson_Creek', label: '(GMT-07:00) Dawson Creek' },
    { value: 'America/Denver', label: '(GMT-06:00) Denver' },
    { value: 'America/Detroit', label: '(GMT-04:00) Detroit' },
    { value: 'America/Dominica', label: '(GMT-04:00) Dominica' },
    { value: 'America/Edmonton', label: '(GMT-06:00) Edmonton' },
    { value: 'America/Eirunepe', label: '(GMT-05:00) Eirunepe' },
    { value: 'America/El_Salvador', label: '(GMT-06:00) El Salvador' },
    { value: 'America/Fort_Nelson', label: '(GMT-07:00) Fort Nelson' },
    { value: 'America/Fortaleza', label: '(GMT-03:00) Fortaleza' },
    { value: 'America/Glace_Bay', label: '(GMT-03:00) Glace Bay' },
    { value: 'America/Goose_Bay', label: '(GMT-03:00) Goose Bay' },
    { value: 'America/Grand_Turk', label: '(GMT-04:00) Grand Turk' },
    { value: 'America/Grenada', label: '(GMT-04:00) Grenada' },
    { value: 'America/Guadeloupe', label: '(GMT-04:00) Guadeloupe' },
    { value: 'America/Guatemala', label: '(GMT-06:00) Guatemala' },
    { value: 'America/Guayaquil', label: '(GMT-05:00) Guayaquil' },
    { value: 'America/Guyana', label: '(GMT-04:00) Guyana' },
    { value: 'America/Halifax', label: '(GMT-03:00) Halifax' },
    { value: 'America/Havana', label: '(GMT-04:00) Havana' },
    { value: 'America/Hermosillo', label: '(GMT-07:00) Hermosillo' },
    { value: 'America/Indiana/Indianapolis', label: '(GMT-04:00) Indiana/Indianapolis' },
    { value: 'America/Indiana/Knox', label: '(GMT-05:00) Indiana/Knox' },
    { value: 'America/Indiana/Marengo', label: '(GMT-04:00) Indiana/Marengo' },
    { value: 'America/Indiana/Petersburg', label: '(GMT-04:00) Indiana/Petersburg' },
    { value: 'America/Indiana/Tell_City', label: '(GMT-05:00) Indiana/Tell City' },
    { value: 'America/Indiana/Vevay', label: '(GMT-04:00) Indiana/Vevay' },
    { value: 'America/Indiana/Vincennes', label: '(GMT-04:00) Indiana/Vincennes' },
    { value: 'America/Indiana/Winamac', label: '(GMT-04:00) Indiana/Winamac' },
    { value: 'America/Inuvik', label: '(GMT-06:00) Inuvik' },
    { value: 'America/Iqaluit', label: '(GMT-04:00) Iqaluit' },
    { value: 'America/Jamaica', label: '(GMT-05:00) Jamaica' },
    { value: 'America/Juneau', label: '(GMT-08:00) Juneau' },
    { value: 'America/Kentucky/Louisville', label: '(GMT-04:00) Kentucky/Louisville' },
    { value: 'America/Kentucky/Monticello', label: '(GMT-04:00) Kentucky/Monticello' },
    { value: 'America/Kralendijk', label: '(GMT-04:00) Kralendijk' },
    { value: 'America/La_Paz', label: '(GMT-04:00) La Paz' },
    { value: 'America/Lima', label: '(GMT-05:00) Lima' },
    { value: 'America/Los_Angeles', label: '(GMT-07:00) Los Angeles' },
    { value: 'America/Lower_Princes', label: '(GMT-04:00) Lower Princes' },
    { value: 'America/Maceio', label: '(GMT-03:00) Maceio' },
    { value: 'America/Managua', label: '(GMT-06:00) Managua' },
    { value: 'America/Manaus', label: '(GMT-04:00) Manaus' },
    { value: 'America/Marigot', label: '(GMT-04:00) Marigot' },
    { value: 'America/Martinique', label: '(GMT-04:00) Martinique' },
    { value: 'America/Matamoros', label: '(GMT-05:00) Matamoros' },
    { value: 'America/Mazatlan', label: '(GMT-07:00) Mazatlan' },
    { value: 'America/Menominee', label: '(GMT-05:00) Menominee' },
    { value: 'America/Merida', label: '(GMT-06:00) Merida' },
    { value: 'America/Metlakatla', label: '(GMT-08:00) Metlakatla' },
    { value: 'America/Mexico_City', label: '(GMT-06:00) Mexico City' },
    { value: 'America/Miquelon', label: '(GMT-02:00) Miquelon' },
    { value: 'America/Moncton', label: '(GMT-03:00) Moncton' },
    { value: 'America/Monterrey', label: '(GMT-06:00) Monterrey' },
    { value: 'America/Montevideo', label: '(GMT-03:00) Montevideo' },
    { value: 'America/Montserrat', label: '(GMT-04:00) Montserrat' },
    { value: 'America/Nassau', label: '(GMT-04:00) Nassau' },
    { value: 'America/New_York', label: '(GMT-04:00) New York' },
    { value: 'America/Nome', label: '(GMT-08:00) Nome' },
    { value: 'America/Noronha', label: '(GMT-02:00) Noronha' },
    { value: 'America/North_Dakota/Beulah', label: '(GMT-05:00) North Dakota/Beulah' },
    { value: 'America/North_Dakota/Center', label: '(GMT-05:00) North Dakota/Center' },
    { value: 'America/North_Dakota/New_Salem', label: '(GMT-05:00) North Dakota/New Salem' },
    { value: 'America/Nuuk', label: '(GMT-02:00) Nuuk' },
    { value: 'America/Ojinaga', label: '(GMT-05:00) Ojinaga' },
    { value: 'America/Panama', label: '(GMT-05:00) Panama' },
    { value: 'America/Paramaribo', label: '(GMT-03:00) Paramaribo' },
    { value: 'America/Phoenix', label: '(GMT-07:00) Phoenix' },
    { value: 'America/Port-au-Prince', label: '(GMT-04:00) Port-au-Prince' },
    { value: 'America/Port_of_Spain', label: '(GMT-04:00) Port of Spain' },
    { value: 'America/Porto_Velho', label: '(GMT-04:00) Porto Velho' },
    { value: 'America/Puerto_Rico', label: '(GMT-04:00) Puerto Rico' },
    { value: 'America/Punta_Arenas', label: '(GMT-03:00) Punta Arenas' },
    { value: 'America/Rankin_Inlet', label: '(GMT-05:00) Rankin Inlet' },
    { value: 'America/Recife', label: '(GMT-03:00) Recife' },
    { value: 'America/Regina', label: '(GMT-06:00) Regina' },
    { value: 'America/Resolute', label: '(GMT-05:00) Resolute' },
    { value: 'America/Rio_Branco', label: '(GMT-05:00) Rio Branco' },
    { value: 'America/Santarem', label: '(GMT-03:00) Santarem' },
    { value: 'America/Santiago', label: '(GMT-04:00) Santiago' },
    { value: 'America/Santo_Domingo', label: '(GMT-04:00) Santo Domingo' },
    { value: 'America/Sao_Paulo', label: '(GMT-03:00) Sao Paulo' },
    { value: 'America/Scoresbysund', label: '(GMT+00:00) Scoresbysund' },
    { value: 'America/Sitka', label: '(GMT-08:00) Sitka' },
    { value: 'America/St_Barthelemy', label: '(GMT-04:00) St. Barthelemy' },
    { value: 'America/St_Johns', label: '(GMT-02:30) St. Johns' },
    { value: 'America/St_Kitts', label: '(GMT-04:00) St. Kitts' },
    { value: 'America/St_Lucia', label: '(GMT-04:00) St. Lucia' },
    { value: 'America/St_Thomas', label: '(GMT-04:00) St. Thomas' },
    { value: 'America/St_Vincent', label: '(GMT-04:00) St. Vincent' },
    { value: 'America/Swift_Current', label: '(GMT-06:00) Swift Current' },
    { value: 'America/Tegucigalpa', label: '(GMT-06:00) Tegucigalpa' },
    { value: 'America/Thule', label: '(GMT-03:00) Thule' },
    { value: 'America/Tijuana', label: '(GMT-07:00) Tijuana' },
    { value: 'America/Toronto', label: '(GMT-04:00) Toronto' },
    { value: 'America/Tortola', label: '(GMT-04:00) Tortola' },
    { value: 'America/Vancouver', label: '(GMT-07:00) Vancouver' },
    { value: 'America/Whitehorse', label: '(GMT-07:00) Whitehorse' },
    { value: 'America/Winnipeg', label: '(GMT-05:00) Winnipeg' },
    { value: 'America/Yakutat', label: '(GMT-08:00) Yakutat' },
    { value: 'Antarctica/Casey', label: '(GMT+11:00) Casey' },
    { value: 'Antarctica/Davis', label: '(GMT+07:00) Davis' },
    { value: 'Antarctica/DumontDUrville', label: '(GMT+10:00) DumontDUrville' },
    { value: 'Antarctica/Macquarie', label: '(GMT+10:00) Macquarie' },
    { value: 'Antarctica/Mawson', label: '(GMT+05:00) Mawson' },
    { value: 'Antarctica/McMurdo', label: '(GMT+12:00) McMurdo' },
    { value: 'Antarctica/Palmer', label: '(GMT-03:00) Palmer' },
    { value: 'Antarctica/Rothera', label: '(GMT-03:00) Rothera' },
    { value: 'Antarctica/Syowa', label: '(GMT+03:00) Syowa' },
    { value: 'Antarctica/Troll', label: '(GMT+02:00) Troll' },
    { value: 'Antarctica/Vostok', label: '(GMT+06:00) Vostok' },
    { value: 'Arctic/Longyearbyen', label: '(GMT+02:00) Longyearbyen' },
    { value: 'Asia/Aden', label: '(GMT+03:00) Aden' },
    { value: 'Asia/Almaty', label: '(GMT+05:00) Almaty' },
    { value: 'Asia/Amman', label: '(GMT+03:00) Amman' },
    { value: 'Asia/Anadyr', label: '(GMT+12:00) Anadyr' },
    { value: 'Asia/Aqtau', label: '(GMT+05:00) Aqtau' },
    { value: 'Asia/Aqtobe', label: '(GMT+05:00) Aqtobe' },
    { value: 'Asia/Ashgabat', label: '(GMT+05:00) Ashgabat' },
    { value: 'Asia/Atyrau', label: '(GMT+05:00) Atyrau' },
    { value: 'Asia/Baghdad', label: '(GMT+03:00) Baghdad' },
    { value: 'Asia/Bahrain', label: '(GMT+03:00) Bahrain' },
    { value: 'Asia/Baku', label: '(GMT+04:00) Baku' },
    { value: 'Asia/Bangkok', label: '(GMT+07:00) Bangkok' },
    { value: 'Asia/Barnaul', label: '(GMT+07:00) Barnaul' },
    { value: 'Asia/Beirut', label: '(GMT+03:00) Beirut' },
    { value: 'Asia/Bishkek', label: '(GMT+06:00) Bishkek' },
    { value: 'Asia/Brunei', label: '(GMT+08:00) Brunei' },
    { value: 'Asia/Chita', label: '(GMT+09:00) Chita' },
    { value: 'Asia/Choibalsan', label: '(GMT+08:00) Choibalsan' },
    { value: 'Asia/Colombo', label: '(GMT+05:30) Colombo' },
    { value: 'Asia/Damascus', label: '(GMT+03:00) Damascus' },
    { value: 'Asia/Dhaka', label: '(GMT+06:00) Dhaka' },
    { value: 'Asia/Dili', label: '(GMT+09:00) Dili' },
    { value: 'Asia/Dubai', label: '(GMT+04:00) Dubai' },
    { value: 'Asia/Dushanbe', label: '(GMT+05:00) Dushanbe' },
    { value: 'Asia/Famagusta', label: '(GMT+03:00) Famagusta' },
    { value: 'Asia/Gaza', label: '(GMT+03:00) Gaza' },
    { value: 'Asia/Hebron', label: '(GMT+03:00) Hebron' },
    { value: 'Asia/Ho_Chi_Minh', label: '(GMT+07:00) Ho Chi Minh' },
    { value: 'Asia/Hong_Kong', label: '(GMT+08:00) Hong Kong' },
    { value: 'Asia/Hovd', label: '(GMT+07:00) Hovd' },
    { value: 'Asia/Irkutsk', label: '(GMT+08:00) Irkutsk' },
    { value: 'Asia/Jakarta', label: '(GMT+07:00) Jakarta' },
    { value: 'Asia/Jayapura', label: '(GMT+09:00) Jayapura' },
    { value: 'Asia/Jerusalem', label: '(GMT+03:00) Jerusalem' },
    { value: 'Asia/Kabul', label: '(GMT+04:30) Kabul' },
    { value: 'Asia/Kamchatka', label: '(GMT+12:00) Kamchatka' },
    { value: 'Asia/Karachi', label: '(GMT+05:00) Karachi' },
    { value: 'Asia/Kathmandu', label: '(GMT+05:45) Kathmandu' },
    { value: 'Asia/Khandyga', label: '(GMT+09:00) Khandyga' },
    { value: 'Asia/Kolkata', label: '(GMT+05:30) Kolkata' },
    { value: 'Asia/Krasnoyarsk', label: '(GMT+07:00) Krasnoyarsk' },
    { value: 'Asia/Kuala_Lumpur', label: '(GMT+08:00) Kuala Lumpur' },
    { value: 'Asia/Kuching', label: '(GMT+08:00) Kuching' },
    { value: 'Asia/Kuwait', label: '(GMT+03:00) Kuwait' },
    { value: 'Asia/Macau', label: '(GMT+08:00) Macau' },
    { value: 'Asia/Magadan', label: '(GMT+11:00) Magadan' },
    { value: 'Asia/Makassar', label: '(GMT+08:00) Makassar' },
    { value: 'Asia/Manila', label: '(GMT+08:00) Manila' },
    { value: 'Asia/Muscat', label: '(GMT+04:00) Muscat' },
    { value: 'Asia/Nicosia', label: '(GMT+03:00) Nicosia' },
    { value: 'Asia/Novokuznetsk', label: '(GMT+07:00) Novokuznetsk' },
    { value: 'Asia/Novosibirsk', label: '(GMT+07:00) Novosibirsk' },
    { value: 'Asia/Omsk', label: '(GMT+06:00) Omsk' },
    { value: 'Asia/Oral', label: '(GMT+05:00) Oral' },
    { value: 'Asia/Phnom_Penh', label: '(GMT+07:00) Phnom Penh' },
    { value: 'Asia/Pontianak', label: '(GMT+07:00) Pontianak' },
    { value: 'Asia/Pyongyang', label: '(GMT+09:00) Pyongyang' },
    { value: 'Asia/Qatar', label: '(GMT+03:00) Qatar' },
    { value: 'Asia/Qostanay', label: '(GMT+06:00) Qostanay' },
    { value: 'Asia/Qyzylorda', label: '(GMT+05:00) Qyzylorda' },
    { value: 'Asia/Riyadh', label: '(GMT+03:00) Riyadh' },
    { value: 'Asia/Sakhalin', label: '(GMT+11:00) Sakhalin' },
    { value: 'Asia/Samarkand', label: '(GMT+05:00) Samarkand' },
    { value: 'Asia/Seoul', label: '(GMT+09:00) Seoul' },
    { value: 'Asia/Shanghai', label: '(GMT+08:00) Shanghai' },
    { value: 'Asia/Singapore', label: '(GMT+08:00) Singapore' },
    { value: 'Asia/Srednekolymsk', label: '(GMT+11:00) Srednekolymsk' },
    { value: 'Asia/Taipei', label: '(GMT+08:00) Taipei' },
    { value: 'Asia/Tashkent', label: '(GMT+05:00) Tashkent' },
    { value: 'Asia/Tbilisi', label: '(GMT+04:00) Tbilisi' },
    { value: 'Asia/Tehran', label: '(GMT+03:30) Tehran' },
    { value: 'Asia/Thimphu', label: '(GMT+06:00) Thimphu' },
    { value: 'Asia/Tokyo', label: '(GMT+09:00) Tokyo' },
    { value: 'Asia/Tomsk', label: '(GMT+07:00) Tomsk' },
    { value: 'Asia/Ulaanbaatar', label: '(GMT+08:00) Ulaanbaatar' },
    { value: 'Asia/Urumqi', label: '(GMT+06:00) Urumqi' },
    { value: 'Asia/Ust-Nera', label: '(GMT+10:00) Ust-Nera' },
    { value: 'Asia/Vientiane', label: '(GMT+07:00) Vientiane' },
    { value: 'Asia/Vladivostok', label: '(GMT+10:00) Vladivostok' },
    { value: 'Asia/Yakutsk', label: '(GMT+09:00) Yakutsk' },
    { value: 'Asia/Yangon', label: '(GMT+06:30) Yangon' },
    { value: 'Asia/Yekaterinburg', label: '(GMT+05:00) Yekaterinburg' },
    { value: 'Asia/Yerevan', label: '(GMT+04:00) Yerevan' },
    { value: 'Atlantic/Azores', label: '(GMT+00:00) Azores' },
    { value: 'Atlantic/Bermuda', label: '(GMT-03:00) Bermuda' },
    { value: 'Atlantic/Canary', label: '(GMT+01:00) Canary' },
    { value: 'Atlantic/Cape_Verde', label: '(GMT-01:00) Cape Verde' },
    { value: 'Atlantic/Faroe', label: '(GMT+01:00) Faroe' },
    { value: 'Atlantic/Madeira', label: '(GMT+01:00) Madeira' },
    { value: 'Atlantic/Reykjavik', label: '(GMT+00:00) Reykjavik' },
    { value: 'Atlantic/South_Georgia', label: '(GMT-02:00) South Georgia' },
    { value: 'Atlantic/St_Helena', label: '(GMT+00:00) St. Helena' },
    { value: 'Atlantic/Stanley', label: '(GMT-03:00) Stanley' },
    { value: 'Australia/Adelaide', label: '(GMT+09:30) Adelaide' },
    { value: 'Australia/Brisbane', label: '(GMT+10:00) Brisbane' },
    { value: 'Australia/Broken_Hill', label: '(GMT+09:30) Broken Hill' },
    { value: 'Australia/Darwin', label: '(GMT+09:30) Darwin' },
    { value: 'Australia/Eucla', label: '(GMT+08:45) Eucla' },
    { value: 'Australia/Hobart', label: '(GMT+10:00) Hobart' },
    { value: 'Australia/Lindeman', label: '(GMT+10:00) Lindeman' },
    { value: 'Australia/Lord_Howe', label: '(GMT+10:30) Lord Howe' },
    { value: 'Australia/Melbourne', label: '(GMT+10:00) Melbourne' },
    { value: 'Australia/Perth', label: '(GMT+08:00) Perth' },
    { value: 'Australia/Sydney', label: '(GMT+10:00) Sydney' },
    { value: 'Europe/Amsterdam', label: '(GMT+02:00) Amsterdam' },
    { value: 'Europe/Andorra', label: '(GMT+02:00) Andorra' },
    { value: 'Europe/Astrakhan', label: '(GMT+04:00) Astrakhan' },
    { value: 'Europe/Athens', label: '(GMT+03:00) Athens' },
    { value: 'Europe/Belgrade', label: '(GMT+02:00) Belgrade' },
    { value: 'Europe/Berlin', label: '(GMT+02:00) Berlin' },
    { value: 'Europe/Bratislava', label: '(GMT+02:00) Bratislava' },
    { value: 'Europe/Brussels', label: '(GMT+02:00) Brussels' },
    { value: 'Europe/Bucharest', label: '(GMT+03:00) Bucharest' },
    { value: 'Europe/Budapest', label: '(GMT+02:00) Budapest' },
    { value: 'Europe/Busingen', label: '(GMT+02:00) Busingen' },
    { value: 'Europe/Chisinau', label: '(GMT+03:00) Chisinau' },
    { value: 'Europe/Copenhagen', label: '(GMT+02:00) Copenhagen' },
    { value: 'Europe/Dublin', label: '(GMT+01:00) Dublin' },
    { value: 'Europe/Gibraltar', label: '(GMT+02:00) Gibraltar' },
    { value: 'Europe/Guernsey', label: '(GMT+01:00) Guernsey' },
    { value: 'Europe/Helsinki', label: '(GMT+03:00) Helsinki' },
    { value: 'Europe/Isle_of_Man', label: '(GMT+01:00) Isle of Man' },
    { value: 'Europe/Istanbul', label: '(GMT+03:00) Istanbul' },
    { value: 'Europe/Jersey', label: '(GMT+01:00) Jersey' },
    { value: 'Europe/Kaliningrad', label: '(GMT+02:00) Kaliningrad' },
    { value: 'Europe/Kirov', label: '(GMT+03:00) Kirov' },
    { value: 'Europe/Kyiv', label: '(GMT+03:00) Kyiv' },
    { value: 'Europe/Lisbon', label: '(GMT+01:00) Lisbon' },
    { value: 'Europe/Ljubljana', label: '(GMT+02:00) Ljubljana' },
    { value: 'Europe/London', label: '(GMT+01:00) London' },
    { value: 'Europe/Luxembourg', label: '(GMT+02:00) Luxembourg' },
    { value: 'Europe/Madrid', label: '(GMT+02:00) Madrid' },
    { value: 'Europe/Malta', label: '(GMT+02:00) Malta' },
    { value: 'Europe/Mariehamn', label: '(GMT+03:00) Mariehamn' },
    { value: 'Europe/Minsk', label: '(GMT+03:00) Minsk' },
    { value: 'Europe/Monaco', label: '(GMT+02:00) Monaco' },
    { value: 'Europe/Moscow', label: '(GMT+03:00) Moscow' },
    { value: 'Europe/Oslo', label: '(GMT+02:00) Oslo' },
    { value: 'Europe/Paris', label: '(GMT+02:00) Paris' },
    { value: 'Europe/Podgorica', label: '(GMT+02:00) Podgorica' },
    { value: 'Europe/Prague', label: '(GMT+02:00) Prague' },
    { value: 'Europe/Riga', label: '(GMT+03:00) Riga' },
    { value: 'Europe/Rome', label: '(GMT+02:00) Rome' },
    { value: 'Europe/Samara', label: '(GMT+04:00) Samara' },
    { value: 'Europe/San_Marino', label: '(GMT+02:00) San Marino' },
    { value: 'Europe/Sarajevo', label: '(GMT+02:00) Sarajevo' },
    { value: 'Europe/Saratov', label: '(GMT+04:00) Saratov' },
    { value: 'Europe/Simferopol', label: '(GMT+03:00) Simferopol' },
    { value: 'Europe/Skopje', label: '(GMT+02:00) Skopje' },
    { value: 'Europe/Sofia', label: '(GMT+03:00) Sofia' },
    { value: 'Europe/Stockholm', label: '(GMT+02:00) Stockholm' },
    { value: 'Europe/Tallinn', label: '(GMT+03:00) Tallinn' },
    { value: 'Europe/Tirane', label: '(GMT+02:00) Tirane' },
    { value: 'Europe/Ulyanovsk', label: '(GMT+04:00) Ulyanovsk' },
    { value: 'Europe/Vaduz', label: '(GMT+02:00) Vaduz' },
    { value: 'Europe/Vatican', label: '(GMT+02:00) Vatican' },
    { value: 'Europe/Vienna', label: '(GMT+02:00) Vienna' },
    { value: 'Europe/Vilnius', label: '(GMT+03:00) Vilnius' },
    { value: 'Europe/Volgograd', label: '(GMT+03:00) Volgograd' },
    { value: 'Europe/Warsaw', label: '(GMT+02:00) Warsaw' },
    { value: 'Europe/Zagreb', label: '(GMT+02:00) Zagreb' },
    { value: 'Europe/Zurich', label: '(GMT+02:00) Zurich' },
    { value: 'Indian/Antananarivo', label: '(GMT+03:00) Antananarivo' },
    { value: 'Indian/Chagos', label: '(GMT+06:00) Chagos' },
    { value: 'Indian/Christmas', label: '(GMT+07:00) Christmas' },
    { value: 'Indian/Cocos', label: '(GMT+06:30) Cocos' },
    { value: 'Indian/Comoro', label: '(GMT+03:00) Comoro' },
    { value: 'Indian/Kerguelen', label: '(GMT+05:00) Kerguelen' },
    { value: 'Indian/Mahe', label: '(GMT+04:00) Mahe' },
    { value: 'Indian/Maldives', label: '(GMT+05:00) Maldives' },
    { value: 'Indian/Mauritius', label: '(GMT+04:00) Mauritius' },
    { value: 'Indian/Mayotte', label: '(GMT+03:00) Mayotte' },
    { value: 'Indian/Reunion', label: '(GMT+04:00) Reunion' },
    { value: 'Pacific/Apia', label: '(GMT+13:00) Apia' },
    { value: 'Pacific/Auckland', label: '(GMT+12:00) Auckland' },
    { value: 'Pacific/Bougainville', label: '(GMT+11:00) Bougainville' },
    { value: 'Pacific/Chatham', label: '(GMT+12:45) Chatham' },
    { value: 'Pacific/Chuuk', label: '(GMT+10:00) Chuuk' },
    { value: 'Pacific/Easter', label: '(GMT-06:00) Easter' },
    { value: 'Pacific/Efate', label: '(GMT+11:00) Efate' },
    { value: 'Pacific/Enderbury', label: '(GMT+13:00) Enderbury' },
    { value: 'Pacific/Fakaofo', label: '(GMT+13:00) Fakaofo' },
    { value: 'Pacific/Fiji', label: '(GMT+12:00) Fiji' },
    { value: 'Pacific/Funafuti', label: '(GMT+12:00) Funafuti' },
    { value: 'Pacific/Galapagos', label: '(GMT-06:00) Galapagos' },
    { value: 'Pacific/Gambier', label: '(GMT-09:00) Gambier' },
    { value: 'Pacific/Guadalcanal', label: '(GMT+11:00) Guadalcanal' },
    { value: 'Pacific/Guam', label: '(GMT+10:00) Guam' },
    { value: 'Pacific/Honolulu', label: '(GMT-10:00) Honolulu' },
    { value: 'Pacific/Kanton', label: '(GMT+13:00) Kanton' },
    { value: 'Pacific/Kiritimati', label: '(GMT+14:00) Kiritimati' },
    { value: 'Pacific/Kosrae', label: '(GMT+11:00) Kosrae' },
    { value: 'Pacific/Kwajalein', label: '(GMT+12:00) Kwajalein' },
    { value: 'Pacific/Majuro', label: '(GMT+12:00) Majuro' },
    { value: 'Pacific/Marquesas', label: '(GMT-09:30) Marquesas' },
    { value: 'Pacific/Midway', label: '(GMT-11:00) Midway' },
    { value: 'Pacific/Nauru', label: '(GMT+12:00) Nauru' },
    { value: 'Pacific/Niue', label: '(GMT-11:00) Niue' },
    { value: 'Pacific/Norfolk', label: '(GMT+11:00) Norfolk' },
    { value: 'Pacific/Noumea', label: '(GMT+11:00) Noumea' },
    { value: 'Pacific/Pago_Pago', label: '(GMT-11:00) Pago Pago' },
    { value: 'Pacific/Palau', label: '(GMT+09:00) Palau' },
    { value: 'Pacific/Pitcairn', label: '(GMT-08:00) Pitcairn' },
    { value: 'Pacific/Pohnpei', label: '(GMT+11:00) Pohnpei' },
    { value: 'Pacific/Port_Moresby', label: '(GMT+10:00) Port Moresby' },
    { value: 'Pacific/Rarotonga', label: '(GMT-10:00) Rarotonga' },
    { value: 'Pacific/Saipan', label: '(GMT+10:00) Saipan' },
    { value: 'Pacific/Tahiti', label: '(GMT-10:00) Tahiti' },
    { value: 'Pacific/Tarawa', label: '(GMT+12:00) Tarawa' },
    { value: 'Pacific/Tongatapu', label: '(GMT+13:00) Tongatapu' },
    { value: 'Pacific/Wake', label: '(GMT+12:00) Wake' },
    { value: 'Pacific/Wallis', label: '(GMT+12:00) Wallis' },
];

export const countryToTimezone: { [key: string]: string } = {
  "Andorra": "Europe/Andorra",
  "United Arab Emirates": "Asia/Dubai",
  "Afghanistan": "Asia/Kabul",
  "Antigua and Barbuda": "America/Antigua",
  "Albania": "Europe/Tirane",
  "Armenia": "Asia/Yerevan",
  "Angola": "Africa/Luanda",
  "Argentina": "America/Argentina/Buenos_Aires",
  "Austria": "Europe/Vienna",
  "Australia": "Australia/Sydney",
  "Azerbaijan": "Asia/Baku",
  "Bosnia and Herzegovina": "Europe/Sarajevo",
  "Barbados": "America/Barbados",
  "Bangladesh": "Asia/Dhaka",
  "Belgium": "Europe/Brussels",
  "Burkina Faso": "Africa/Ouagadougou",
  "Bulgaria": "Europe/Sofia",
  "Bahrain": "Asia/Bahrain",
  "Burundi": "Africa/Bujumbura",
  "Benin": "Africa/Porto-Novo",
  "Brunei": "Asia/Brunei",
  "Bolivia": "America/La_Paz",
  "Brazil": "America/Sao_Paulo",
  "Bahamas": "America/Nassau",
  "Bhutan": "Asia/Thimphu",
  "Botswana": "Africa/Gaborone",
  "Belarus": "Europe/Minsk",
  "Belize": "America/Belize",
  "Canada": "America/Toronto",
  "Congo, Democratic Republic of the": "Africa/Kinshasa",
  "Central African Republic": "Africa/Bangui",
  "Congo, Republic of the": "Africa/Brazzaville",
  "Switzerland": "Europe/Zurich",
  "Cote d'Ivoire": "Africa/Abidjan",
  "Chile": "America/Santiago",
  "Cameroon": "Africa/Douala",
  "China": "Asia/Shanghai",
  "Colombia": "America/Bogota",
  "Costa Rica": "America/Costa_Rica",
  "Cuba": "America/Havana",
  "Cabo Verde": "Atlantic/Cape_Verde",
  "Cyprus": "Asia/Nicosia",
  "Czech Republic": "Europe/Prague",
  "Germany": "Europe/Berlin",
  "Djibouti": "Africa/Djibouti",
  "Denmark": "Europe/Copenhagen",
  "Dominica": "America/Dominica",
  "Dominican Republic": "America/Santo_Domingo",
  "Algeria": "Africa/Algiers",
  "Ecuador": "America/Guayaquil",
  "Estonia": "Europe/Tallinn",
  "Egypt": "Africa/Cairo",
  "Eritrea": "Africa/Asmara",
  "Spain": "Europe/Madrid",
  "Ethiopia": "Africa/Addis_Ababa",
  "Finland": "Europe/Helsinki",
  "Fiji": "Pacific/Fiji",
  "Micronesia": "Pacific/Chuuk",
  "France": "Europe/Paris",
  "Gabon": "Africa/Libreville",
  "United Kingdom": "Europe/London",
  "Grenada": "America/Grenada",
  "Georgia": "Asia/Tbilisi",
  "Ghana": "Africa/Accra",
  "Gambia": "Africa/Banjul",
  "Guinea": "Africa/Conakry",
  "Equatorial Guinea": "Africa/Malabo",
  "Greece": "Europe/Athens",
  "Guatemala": "America/Guatemala",
  "Guinea-Bissau": "Africa/Bissau",
  "Guyana": "America/Guyana",
  "Honduras": "America/Tegucigalpa",
  "Croatia": "Europe/Zagreb",
  "Haiti": "America/Port-au-Prince",
  "Hungary": "Europe/Budapest",
  "Indonesia": "Asia/Jakarta",
  "Ireland": "Europe/Dublin",
  "Israel": "Asia/Jerusalem",
  "India": "Asia/Kolkata",
  "Iraq": "Asia/Baghdad",
  "Iran": "Asia/Tehran",
  "Iceland": "Atlantic/Reykjavik",
  "Italy": "Europe/Rome",
  "Jamaica": "America/Jamaica",
  "Jordan": "Asia/Amman",
  "Japan": "Asia/Tokyo",
  "Kenya": "Africa/Nairobi",
  "Kyrgyzstan": "Asia/Bishkek",
  "Cambodia": "Asia/Phnom_Penh",
  "Kiribati": "Pacific/Tarawa",
  "Comoros": "Indian/Comoro",
  "Saint Kitts and Nevis": "America/St_Kitts",
  "North Korea": "Asia/Pyongyang",
  "South Korea": "Asia/Seoul",
  "Kuwait": "Asia/Kuwait",
  "Kazakhstan": "Asia/Almaty",
  "Laos": "Asia/Vientiane",
  "Lebanon": "Asia/Beirut",
  "Saint Lucia": "America/St_Lucia",
  "Liechtenstein": "Europe/Vaduz",
  "Sri Lanka": "Asia/Colombo",
  "Liberia": "Africa/Monrovia",
  "Lesotho": "Africa/Maseru",
  "Lithuania": "Europe/Vilnius",
  "Luxembourg": "Europe/Luxembourg",
  "Latvia": "Europe/Riga",
  "Libya": "Africa/Tripoli",
  "Morocco": "Africa/Casablanca",
  "Monaco": "Europe/Monaco",
  "Moldova": "Europe/Chisinau",
  "Montenegro": "Europe/Podgorica",
  "Madagascar": "Indian/Antananarivo",
  "Marshall Islands": "Pacific/Majuro",
  "North Macedonia": "Europe/Skopje",
  "Mali": "Africa/Bamako",
  "Myanmar": "Asia/Yangon",
  "Mongolia": "Asia/Ulaanbaatar",
  "Mauritania": "Africa/Nouakchott",
  "Malta": "Europe/Malta",
  "Mauritius": "Indian/Mauritius",
  "Maldives": "Indian/Maldives",
  "Malawi": "Africa/Blantyre",
  "Mexico": "America/Mexico_City",
  "Malaysia": "Asia/Kuala_Lumpur",
  "Mozambique": "Africa/Maputo",
  "Namibia": "Africa/Windhoek",
  "Niger": "Africa/Niamey",
  "Nigeria": "Africa/Lagos",
  "Nicaragua": "America/Managua",
  "Netherlands": "Europe/Amsterdam",
  "Norway": "Europe/Oslo",
  "Nepal": "Asia/Kathmandu",
  "Nauru": "Pacific/Nauru",
  "New Zealand": "Pacific/Auckland",
  "Oman": "Asia/Muscat",
  "Panama": "America/Panama",
  "Peru": "America/Lima",
  "Papua New Guinea": "Pacific/Port_Moresby",
  "Philippines": "Asia/Manila",
  "Pakistan": "Asia/Karachi",
  "Poland": "Europe/Warsaw",
  "Portugal": "Europe/Lisbon",
  "Palau": "Pacific/Palau",
  "Paraguay": "America/Asuncion",
  "Qatar": "Asia/Qatar",
  "Romania": "Europe/Bucharest",
  "Serbia": "Europe/Belgrade",
  "Russia": "Europe/Moscow",
  "Rwanda": "Africa/Kigali",
  "Saudi Arabia": "Asia/Riyadh",
  "Solomon Islands": "Pacific/Guadalcanal",
  "Seychelles": "Indian/Mahe",
  "Sudan": "Africa/Khartoum",
  "Sweden": "Europe/Stockholm",
  "Singapore": "Asia/Singapore",
  "Slovenia": "Europe/Ljubljana",
  "Slovakia": "Europe/Bratislava",
  "Sierra Leone": "Africa/Freetown",
  "San Marino": "Europe/San_Marino",
  "Senegal": "Africa/Dakar",
  "Somalia": "Africa/Mogadishu",
  "Suriname": "America/Paramaribo",
  "South Sudan": "Africa/Juba",
  "Sao Tome and Principe": "Africa/Sao_Tome",
  "El Salvador": "America/El_Salvador",
  "Syria": "Asia/Damascus",
  "Eswatini": "Africa/Mbabane",
  "Chad": "Africa/Ndjamena",
  "Togo": "Africa/Lome",
  "Thailand": "Asia/Bangkok",
  "Tajikistan": "Asia/Dushanbe",
  "Timor-Leste": "Asia/Dili",
  "Turkmenistan": "Asia/Ashgabat",
  "Tunisia": "Africa/Tunis",
  "Tonga": "Pacific/Tongatapu",
  "Turkey": "Europe/Istanbul",
  "Trinidad and Tobago": "America/Port_of_Spain",
  "Tuvalu": "Pacific/Funafuti",
  "Taiwan": "Asia/Taipei",
  "Tanzania": "Africa/Dar_es_Salaam",
  "Ukraine": "Europe/Kyiv",
  "Uganda": "Africa/Kampala",
  "United States": "America/New_York",
  "Uruguay": "America/Montevideo",
  "Uzbekistan": "Asia/Tashkent",
  "Vatican City": "Europe/Vatican",
  "Saint Vincent and the Grenadines": "America/St_Vincent",
  "Venezuela": "America/Caracas",
  "Vietnam": "Asia/Ho_Chi_Minh",
  "Vanuatu": "Pacific/Efate",
  "Samoa": "Pacific/Apia",
  "Kosovo": "Europe/Belgrade",
  "Yemen": "Asia/Aden",
  "South Africa": "Africa/Johannesburg",
  "Zambia": "Africa/Lusaka",
  "Zimbabwe": "Africa/Harare"
};
